// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emvlgdjjcjblgefmgvqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtdmxnZGpqY2pibGdlZm1ndnFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2MDA3NzEsImV4cCI6MjA1MjE3Njc3MX0.oE3fxlRAiIykEExiwE_PYxH1Mt3r8lHMpkjelb1wMWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);